(php) {
	# Configures multiple PHP-related settings
	# https://caddyserver.com/docs/caddyfile/directives/php_fastcgi
	# php_fastcgi unix//var/run/php-fpm.sock
	php_fastcgi unix//var/run/php-fpm.sock {
		# root /var/www/html/public
		dial_timeout 10s
		read_timeout 180s
		write_timeout 180s
	}
}

# https://caddy2.dengxiaolong.com/docs/caddyfile/concepts#addresses
# 如果你的站点地址包含主机名或 IP 地址，则会启用自动HTTPS。然而，这种行为纯粹是隐含的，因此它永远不会覆盖任何显式配置。例如，如果站点的地址是http://example.com，则不会激活自动HTTPS，因为该方案是明确的http://。
# 比如：如下配置地址，就会导致启用自动HTTPS
# example.com, http://localhost, https://localhost {

# 如下配置地址，就【不会】启用自动HTTPS
# http://example.com, http://localhost {
:80, :443 {
	import common

	root * /app/web
	# https://caddyserver.com/docs/caddyfile/directives/request_body
	request_body {
		max_size 20MB
	}

	#	# Configures multiple PHP-related settings
	#	# https://caddyserver.com/docs/caddyfile/directives/php_fastcgi
	#	# php_fastcgi unix//var/run/php-fpm.sock
	# 写法1：
	#	php_fastcgi unix//var/run/php-fpm.sock {
	#		dial_timeout 10s
	#		read_timeout 180s
	#		write_timeout 180s
	#	}
	# 写法2：
	import php
	# reverse_proxy /api/* localhost:9001
	file_server
	# handle VS handler_path
	# handle /bar/* {
	# 	# 路径仍然保留了"/bar"
	# }
	# handle_path /foo/* {
	# 	# 路径有"/foo"前缀的将被去除
	# }
	# handle_path /api/* {
	# 	# 路径有"/api"前缀的将被去除
	# 	import php
	# }
	handle_errors {
		respond "{err.status_code} {err.status_text}" # eg. "404 Not Found"
	}

	log {
		# output file /var/log/caddy/example.access.log
		output file /var/log/caddy/example.com.log
		format console
		level INFO
	}

	# Encode responses in zstd or gzip, depending on the availability indicated by the browser.
	# encode zstd br gzip
	encode zstd gzip

	# Prevent access to dot-files, except .well-known
	@dotFiles {
		path */.*
		not path /.well-known/*
	}

	# defined a named matcher
	@static_404 {
		path_regexp \.(jpg|jpeg|png|webp|gif|avif|ico|svg|css|js|gz|eot|ttf|otf|woff|woff2|pdf)$
		not file
	}
	# https://caddyserver.com/docs/caddyfile/directives/respond
	respond @static_404 "Static resources Not Found" 404 {
		close
	}
}
